version: '3.8'
services:

  db:
    image: postgres:13
    restart: always
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - src/.env

  factory_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: factory
    env_file:
      - src/.env
    volumes:
      - ./src:/app
    depends_on:
      - db

volumes:
  postgres_data: